### ISSUE TITLE
Sample build stage failed with many errors

### ISSUE THREAD

**Issue by zen** [Toroid-io/drone-kicad#10]
Hi,

First - thank you for the great project! I was just playing with it with your sample (https://github.com/Toroid-io/drone-kicad-sample) and ran across many errors:
`+ /bin/sh -c cd /usr/share/kicad/library && git clone https://github.com/Toroid-io/toroid-kicad-library.git
Cloning into 'toroid-kicad-library'...
+ /bin/sh -c cd /usr/share/kicad/template && git clone https://github.com/Toroid-io/toroid-kicad-templates.git
Cloning into 'toroid-kicad-templates'...
+ python2 -u /bin/ci-scripts/export_schematic.py drone-kicad-sample
Initial recording window is set to:
X:0   Y:0    Width:800    Height:600
Adjusted recording window is set to:
X:0   Y:4    Width:800    Height:592
Your window manager appears to be Unknown

Initializing...
Output file: /drone/src/bitbucket.org/surge-cloud/ci-test/CI-BUILD/drone-kicad-sample/SCH/export_schematic_screencast.ogv
Capturing!

(eeschema:133): Gtk-WARNING **: 23:52:23.829: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.3A4GRZ?: No such file or directory

(eeschema:133): Gtk-WARNING **: 23:52:23.830: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
INFO:__main__:Open File->Print
INFO:export_util:Waiting for print window...
INFO:export_util:Found print window
INFO:__main__:Set color output
INFO:__main__:Open Print dialog
INFO:__main__:Enter build output directory

** (eeschema:133): WARNING **: 23:52:33.788: Couldn't connect to D-Bus system bus, Could not connect: No such file or directory
INFO:export_util:Waiting for print window...
INFO:export_util:Found print window
INFO:__main__:Print!
INFO:__main__:Wait before shutdown
Shutting down....
   
Done.
Written 441632 bytes
(441632 of which were video data and 0 audio data)

..
Goodbye!
+ python2 -u /bin/ci-scripts/delete_footprints.py --brd drone-kicad-sample --footprints R1,C1,R2,C2 --variant Variant_1
Removing C2
Removing C1
Removing R2
Removing R1
Initial recording window is set to:
X:0   Y:0    Width:800    Height:600
Adjusted recording window is set to:
X:0   Y:4    Width:800    Height:592
Your window manager appears to be Unknown

Initializing...
Output file: /drone/src/bitbucket.org/surge-cloud/ci-test/CI-BUILD/drone-kicad-sample_Variant_1/DLF/dlfVariant_1.ogv
Capturing!

(pcbnew:174): Gtk-WARNING **: 23:52:47.453: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.0WYPRZ?: No such file or directory

(pcbnew:174): Gtk-WARNING **: 23:52:47.454: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
INFO:__main__:Open Edit -> Cleanup tracks and vias
INFO:export_util:Waiting for cleanup window...

(pcbnew:174): Gtk-WARNING **: 23:52:56.678: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.A8PJRZ?: No such file or directory

(pcbnew:174): Gtk-WARNING **: 23:52:56.682: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
Shutting down....
   
Done.
Written 2455797 bytes
(2455797 of which were video data and 0 audio data)

..
Goodbye!
Traceback (most recent call last):
  File "/bin/ci-scripts/delete_footprints.py", line 112, in <module>
    main(sys.argv[1:])
  File "/bin/ci-scripts/delete_footprints.py", line 109, in main
    cleanup(args)
  File "/bin/ci-scripts/delete_footprints.py", line 92, in cleanup
    pcbnew_cleanup(args.footprints)
  File "/bin/ci-scripts/delete_footprints.py", line 45, in pcbnew_cleanup
    wait_for_window('cleanup', 'Cleaning Options')
  File "/usr/bin/ci-scripts/export_util.py", line 63, in wait_for_window
    raise RuntimeError('Timed out waiting for %s window' % name)
RuntimeError: Timed out waiting for cleanup window
exit status 1`

Any ideas how to debug it?

**Comment by andresmanelli** [comment]
Hello!

I forgot to update `.drone.yml` for the sample project. Could you try to change the version of the image to `0.5.3`?

Also, maybe our server is a little bit slow. Try to add a `wait` parameter of 15 or 20 seconds.

Let me know if it works for you!

**Comment by zen** [comment]
Thanks!
Unfortunely, I'm getting this:

```
+ /bin/sh -c cd /usr/share/kicad/library && git clone https://github.com/Toroid-io/toroid-kicad-library.git
Cloning into 'toroid-kicad-library'...
+ /bin/sh -c cd /usr/share/kicad/template && git clone https://github.com/Toroid-io/toroid-kicad-templates.git
Cloning into 'toroid-kicad-templates'...
+ python2 -u /bin/ci-scripts/export_schematic.py drone-kicad-sample
Traceback (most recent call last):
  File "/bin/ci-scripts/export_schematic.py", line 104, in <module>
    if sys.argv[2]:
IndexError: list index out of range
exit status 1
```

**Comment by andresmanelli** [comment]
I think I should modify that script. For the moment could you try adding the `wait` parameter for the project & variants?

**Comment by zen** [comment]
Can I pass it somehow or should I rebuild docker image (sorry, still figuring out drone internals)

**Comment by andresmanelli** [comment]
Yes, it is shown in the README of this repo. It's a parameter in the `options` group in your `.drone.yml`. No need to rebuild the image.

**Comment by andresmanelli** [comment]
Please try now with `toroid/drone-kicad:0.5.4`, and let me know how it goes.
Demo board built successfully (generated files [here](https://cloud.toroid.io/index.php/s/FroTFFwX7y8H9db))

**Comment by zen** [comment]
Awesome, worked like a charm. I have some ideas how to extend it, will try to implement it myself and create pull request

**Comment by andresmanelli** [comment]
That would be great! I'm closing this now since it's been resolved.
